version: '3.7'

services:
  mongodb:
    image: "mongo:latest"
    ports:
        - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=pass
        - MONGO_INITDB_DATABASE=gestaogastos
    volumes:
        - ./mongodb/mongodata:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js